[feat] GUI + Installer Infrastructure
weichware10/toolbox pull request #11
Opened 2021-12-17 16:01 UTC by joshuajeschek

2021-12-17 19:52 UTC, TheDarkDesync requested changes

2021-12-17 19:52 UTC, TheDarkDesync commented on README.md
> +- herunterladen der JavaFX-SDK auf [gluonhq.com](https://gluonhq.com/products/javafx/)
```suggestion
- Herunterladen der JavaFX-SDK auf [gluonhq.com](https://gluonhq.com/products/javafx/)
```

2021-12-18 11:52 UTC, grenoui11e approved these changes

2021-12-18 13:34 UTC, TheDarkDesync approved these changes

2021-12-20 11:34 UTC, merged